version: "3.7"

volumes:
  db-data:


networks:
  instavote:
    driver: bridge

services:
  vote:
    image: custlynotts/vote:v8
    ports:
      - 10000:80
    depends_on:
      - redis
    networks:
      - instavote


  redis:
    image: redis:alpine
    networks:
      - instavote


  db:
    image: postgres:10-alpine3.16
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: initcron/result:master
    ports:
      - 10001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: custlynotts/worker:v2
    depends_on:
      - redis
      - db
    networks:
      - instavote
