pipeline {
    
    agent any

    tools {
	maven 'Maven 3.8.6'
	}
    
    stages {
        stage('onne') {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
		sh 'mvn compile'
		}
            }
        }
        
        stage('two') {
            steps {
                echo 'Running Unit tests on worker app'
                dir('worker') {
		sh 'mvn clean test'
            }
            
        }
            stage('three') {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
		sh 'mvn package'
            }
            
        }

    }
    
    post {
        always {
            echo 'Pipeline for worker app is completed...'
        }
    }
}
